services:
  - type: web
    name: superset
    env: docker
    plan: free
    envVars:
      - key: SUPERSET_SECRET_KEY
        value: Hrnd82vMLg03sdh3f4@#@glklvnP9(8347hfJXw0Rbvfa
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: Superset2024!
      - key: ADMIN_EMAIL
        value: admin@example.com